 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/elevator_media", type: :request do
  # ElevatorMedium. As you add validations to ElevatorMedium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ElevatorMedium.create! valid_attributes
      get elevator_media_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      elevator_medium = ElevatorMedium.create! valid_attributes
      get elevator_medium_url(elevator_medium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_elevator_medium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      elevator_medium = ElevatorMedium.create! valid_attributes
      get edit_elevator_medium_url(elevator_medium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ElevatorMedium" do
        expect {
          post elevator_media_url, params: { elevator_medium: valid_attributes }
        }.to change(ElevatorMedium, :count).by(1)
      end

      it "redirects to the created elevator_medium" do
        post elevator_media_url, params: { elevator_medium: valid_attributes }
        expect(response).to redirect_to(elevator_medium_url(ElevatorMedium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ElevatorMedium" do
        expect {
          post elevator_media_url, params: { elevator_medium: invalid_attributes }
        }.to change(ElevatorMedium, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post elevator_media_url, params: { elevator_medium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested elevator_medium" do
        elevator_medium = ElevatorMedium.create! valid_attributes
        patch elevator_medium_url(elevator_medium), params: { elevator_medium: new_attributes }
        elevator_medium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the elevator_medium" do
        elevator_medium = ElevatorMedium.create! valid_attributes
        patch elevator_medium_url(elevator_medium), params: { elevator_medium: new_attributes }
        elevator_medium.reload
        expect(response).to redirect_to(elevator_medium_url(elevator_medium))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        elevator_medium = ElevatorMedium.create! valid_attributes
        patch elevator_medium_url(elevator_medium), params: { elevator_medium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested elevator_medium" do
      elevator_medium = ElevatorMedium.create! valid_attributes
      expect {
        delete elevator_medium_url(elevator_medium)
      }.to change(ElevatorMedium, :count).by(-1)
    end

    it "redirects to the elevator_media list" do
      elevator_medium = ElevatorMedium.create! valid_attributes
      delete elevator_medium_url(elevator_medium)
      expect(response).to redirect_to(elevator_media_url)
    end
  end
end
